### ISSUE TITLE
Setting unknown property: abhimanyu\user\models\User::activation_token

### ISSUE THREAD

**Issue by slvolz** [abhi1693/yii2-app-advanced-startup-kit#2]
After entering in the admin credential information during the installer config, I am getting this error.  More info:

![2015-02-24 22_04_07-unknown property yii_base_unknownpropertyexception](https://cloud.githubusercontent.com/assets/1251618/6356828/24c20faa-bc71-11e4-96e1-1eb798c8baec.png)

**Comment by abhi1693** [comment]
Could you please post your backend log for this issue?

**Comment by abhi1693** [comment]
The issue has been fixed. Update your project using `composer update`. Remove all the tables from the database and run the installer again.
