### ISSUE TITLE
Admin Panel error

### ISSUE THREAD

**Issue by hdushku** [abhi1693/yii2-app-advanced-startup-kit#4]
PHP Fatal Error – yii\base\ErrorException

Class 'COM' not found

**Comment by abhi1693** [comment]
From `PHP 5.4.5`, `COM` is no longer built into the php core. You have to add `COM` support in `php.ini`: 

``` php
[COM_DOT_NET] 
extension=php_com_dotnet.dll 
```

**Comment by hdushku** [comment]
Problem solved
Thanks
