### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by sofer-eg** [abhi1693/yii2-app-advanced-startup-kit#7]
The requested URL /installer/install/index was not found on this server.

Do you have any idea why it happens?

**Comment by abhi1693** [comment]
You can access `/installer/install/index` from the `backend` only. Once the installation is completed successfully, you cannot access the said url. Try accessing the `url` via `backend` and let me know if the problem still persists.

**Comment by sofer-eg** [comment]
Yes, I'm trying this ulr from backend.
Is it correct path in config?

```
'modules'    => [
    'installer' => [
        'class' => \abhimanyu\installer\InstallerModule::className()
    ],
]
```

Here is no directory called `abhimanyu` in `/my-app/backend/` or somewhere else.

**Comment by abhi1693** [comment]
Yes, the paths in the config are all correct. You will find that directory under `vendors`. Have you initialized your application's environment?

**Comment by sofer-eg** [comment]
Yes, I was run init after instalation and select `dev` environment. I configure webserver to access `/my-app/backend/web` directory via `http://backend.my-app.com`, moved `index.php` from `/my-app/backend` to `/my-app/backend/web`, then I open url `http://backend.my-app.com`, and it redirected to `http://backend.my-app.com/installer/install/index`, so `beforeAction` in `/backend/SiteController` works fine.

**Comment by gursel58** [comment]
I have the same problem as sofer-eg had, but I cannot change my url and not sure how to fix the problem. Can you provide some guidance on how to fix the 
/installer/install/index was not found on this server. error.

Thanks
