### ISSUE TITLE
/demo-app/backend/installer/install/index was not found on this server.

### ISSUE THREAD

**Issue by gursel58** [abhi1693/yii2-app-advanced-startup-kit#9]
I noticed that another user had the same issue. I tried to figure what they did and couldnt get it to work.

I am running on Ubuntu 14.04
PHP 5-5-59.1
MySQL

I installed yii2-app-advanced-startup-kit
changed common/config/main.php to include my db settings
ran   sudo php init
ran  sudo ./yii migrate
then opened up a browser window  to http://host/demo-app/    and I got the page with two circles on it
selected the install circle and got the /demo-app/backend/installer/install/index was not found on this server
tried  http://host/demo-app/backend/  and got the same result

I have tried composer update to make sure all dependencies are up to date.

I would appreciate some ideas on how to resolve this.
Thanks

**Comment by abhi1693** [comment]
First of all, you should never include `db` settings manually. This error is shown only when you have not properly initialized your app.

**Comment by gursel58** [comment]
Ok I deleted my earlier attempt and created a new demo-app by composer
I ran sudo php init   set it for a development env
and when I went to   http://host/demo-app
I got this error msg
Database Exception – yii\db\Exception
SQLSTATE[28000] [1045] Access denied for user 'www-data'@'localhost' (using password: NO)

Which lead me earlier to putting in the db information.
What should I do instead ?

**Comment by abhi1693** [comment]
Navigate to `http://host/demo-app/backend` instead

**Comment by gursel58** [comment]
when I goto http://host/demo-app/backend I get this error msg
The requested URL /demo-app/backend/installer/install/index was not found on this server.

**Comment by gursel58** [comment]
I found the issue , I had not setup Apache2 apache2.conf for  AllowOverride All and enabled rewrite.
After I made these changes everything worked.
Thanks
